
### Secret to be passed for Github repo sync for DAGS

apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
  GIT_SYNC_USERNAME: {{arundeep78 | b64enc }}
  GIT_SYNC_PASSWORD: {{ Statik@123 | b64enc }}
