apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-pvc
spec:
  storageClassName: data-postgres-sc 
#  volumeName: data-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi